###
# @name helloworld
GET http://localhost:7070/
Authorization: Bearer xxxxxx

###
# @name helloworld-unauthorized
GET http://localhost:7070/unauthorized
Authorization: Bearer xxxxxx

###
# @name helloworld-status
GET http://localhost:7070/status?code=404
